### ISSUE TITLE
Hover covering file/folder names

### ISSUE THREAD

**Issue by RStrydom** [olmokramer/atom-autohide-tree-view#33]
Hi,
When using the hover activation method, one cannot select a portion of the file or folder at the end of the tree, it is exactly the size of the "closed" tree it seems.

![screen shot 2015-07-26 at 12 03 21 2](https://cloud.githubusercontent.com/assets/5104139/8893380/627e015c-338e-11e5-87b6-4f319182e31e.png)

I am on OSX Yosemite and these are my settings for the package:
Let me know if you require more info.

``` cson
  "autohide-tree-view":
    hiddenWidth: 100
    showOn: "hover"
    animationSpeed: 5
    pushEditor: true
    showPinButton: false
```

Also, was thinking that it would be great if the you added a class to the parent item when the tree is activated, thus styling can be done with less, which in this case I would have just done a `pointer-events: none;` on the hover area when the tree is unhidden.

Thanks again for all your great atom packages

**Comment by olmokramer** [comment]
Hey, thanks for reporting the issue. The width of the hover handle depends on the `hiddenWidth` setting, and I didn't expect people to set `hiddenWidth` to such "high" values :p The fix was pretty easy, just disable the pointer events on the hover area when the tree view opens. If you still want, I can also add classes, but disabling the pointer events is something the package should do by itself in my opinion.

I just published a new version that should fix this problem, please let me know if you're still having issues :)

**Comment by RStrydom** [comment]
Hi, Sorry for the late response, thanks so much. worked like a charm.

Regarding the class, it would more be a feature request for possible theming options. allowing a theme to determine how the tree animates open and closed etc. I do not think it's a feature I would particularly use, but that's only because I do not really change a lot from the original state of the downloaded theme. But for Themers and people who customize their themes a lot, this might be quite useful.

**Comment by olmokramer** [comment]
Well... The animations are done in JS, and trying to change them would probably lead to very weird results. I suppose you can do different background colors or opacity for open/closed tree view, or something like that :p
