### ISSUE TITLE
Tree view appears below tab on spacegray-dark-ui

### ISSUE THREAD

**Issue by lukescott** [olmokramer/atom-autohide-tree-view#51]
Using this theme: https://github.com/cannikin/spacegray-dark-ui/issues

And the tab is appearing above the tree view:
<img width="204" alt="screen shot 2015-09-12 at 5 29 10 pm" src="https://cloud.githubusercontent.com/assets/486224/9834552/d11ac5d6-5973-11e5-81f8-5b3e5e629dc3.png">

This does not happen with the stock Atom Dark theme. I enabled "Push Editor" for now as a workaround.

**Comment by olmokramer** [comment]
Thanks for reporting the issue! Spacegray uses a `z-index: 10;` for the active tab which caused it to render above the tree view. I'll add a super high value to the tree view, because it _should_ be rendered above everything else! There's a couple more issues that I want to solve before releasing, but in the meantime you can add this to your `styles.less`:

``` less
.tree-view-resizer {
  z-index: 100000;
}
```

**Comment by lukescott** [comment]
Awesome! That works (as long as I add `!important` to that).

**Comment by olmokramer** [comment]
Ok, v0.24.4 is published now! Please let me know if it's working alright. (And don't forget to remove the css from your `styles.less` first :p)
