### ISSUE TITLE
Add keyboard shortcut for `pin tree-view`

### ISSUE THREAD

**Issue by scherii** [olmokramer/atom-autohide-tree-view#55]
Please consider adding a keyboard shortcut for easier pinning of the tree-view.

Thank you :)

**Comment by olmokramer** [comment]
I'd rather not add preset keybindings to my packages, because it's a very subjective matter. You can add one yourself easily enough, though. The command to trigger is `autohide-tree-view:toggle-pinned`, but there's also `autohide-tree-view:pin` and `autohide-tree-view:unpin`. To add a keybinding for <kbd>ctrl-h</kbd> that toggles the pinned status, for example, one would add to their `keymap.cson`:

``` cson
'atom-text-editor':
  'ctrl-h': 'autohide-tree-view:toggle-pinned'
```

**Comment by scherii** [comment]
Oh, thank you! That's a great solution.
