### ISSUE TITLE
Atom 1.12.2 - autohide-tree-view doesn't work when mouse at the border of the screen

### ISSUE THREAD

**Issue by dmitrypodshivalov** [olmokramer/atom-autohide-tree-view#80]
Hi, 
Plugin Version: 0.25.1
Atom version 1.12.2

After upgrade of Atom to version 1.12.2, when mouse moved to the left boeder of the screen - nothing happening. 
![2016-11-15 16_37_58-settings](https://cloud.githubusercontent.com/assets/20282784/20312028/3d83852e-ab52-11e6-994e-677cf45823b1.png)

I have to move the pointer few pixels towards right border  - then Tree-view window shows up. 
![2016-11-15 16_38_15-settings](https://cloud.githubusercontent.com/assets/20282784/20312031/3d904fde-ab52-11e6-9a6b-d2c4998777c1.png)

Before upgrade of Atom to version 1.12.2, when I moved mouse pointer to the left border of the screen - the tree-view showed right away. 

It seems that now there is some kind of frame around Atom's window.

Thanks!

**Comment by Ian25** [comment]
I have the same issue.
autohide-tree-view Version: 0.25.1
Atom Version: 1.11.2
Linux Mint

The issue persists on Atom version: 1.12.3

**Comment by ghost** [comment]
You're right -- the tree view's parent element has a 1px left border now, so there's a 1px gap between the edge of the screen and autohide-tree-view's trigger area. For now you can remove the border in your stylesheet:

`atom-panel.panel-left {
  border-left: none;
}`

...or shift the tree view a pixel to the left:

`.tree-view-resizer {
  left: -1px;
}`

Note: shifting just the mouse detection element (.tree-view-autohide-trigger-area) a pixel to the left is a tempting but incomplete fix: The tree view will pop up, but since there is still the 1px gap to the left of the tree view, the tree view will quickly hide again if the cursor is at the edge of the screen.

Hope this helps!

**Comment by dmitrypodshivalov** [comment]
Awesome, I've removed the left border and now it works as is should. 

Thanks a lot!
