### ISSUE TITLE
can't scroll treeview

### ISSUE THREAD

**Issue by mark-hahn** [olmokramer/atom-autohide-tree-view#9]
The treeview closes when I try to scroll using the scrollbar immediately on the right.

**Edit:** There have been an unusual number of bugs/line of code.  Maybe trying to make it pure CSS was a mistake?  (grin)  I'm certainly not saying you have made a lot of mistakes.

**Comment by olmokramer** [comment]
It's actually controlled with JS now instead of CSS. That's when all the trouble started :( But it gives much better control over delays and such.
Anyway, some behavior that hides the tree view when it is blurred (unfocused) interfered with scrollbar dragging. I've added a new setting in `v0.14.3`, `hideOnUnfocus`, to enable/disable this behavior. Please let me know how it works for you
